name: Telegram Reminder

on:
  workflow_dispatch

  schedule:
    - cron: '0 8 * * *'

jobs:
  telegram:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Enviar mensaje a Telegram
        run: |
          curl --fail \
            -X POST \
            "https://api.telegram.org/bot${TOKEN}/sendMessage" \
            --data-urlencode "chat_id=${CHAT_ID}" \
            --data-urlencode "text=🔔 Buenos días Gustavo. Este es un mensaje automático enviado desde GitHub Actions."
