name: Telegram Test

on:
  workflow_dispatch:

jobs:
  telegram:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Comprobar secretos
        run: |
          echo "CHAT=$CHAT_ID"
          echo "TOKEN_LENGTH=${#TOKEN}"

      - name: Test Telegram
        run: |
          curl -v "https://api.telegram.org/bot${TOKEN}/sendMessage" \
            -d "chat_id=${CHAT_ID}" \
            -d "text=Hola desde GitHub"
